      PROGRAM DISPH
C  DISPLAYS NEPTUNE STIS IMAGES FOR CERTAIN SPECTRAL INTERVALS
      INTEGER*2 IM(45,90),IMA(45,91,1800)
      CHARACTER TEXTA(1581120)*10
      EQUIVALENCE (TEXTA(289),IMA)
      OPEN(4,FILE='hnbr',ACCESS='DIRECT',RECL=15811200,FORM=
     &'UNFORMATTED')
      READ(4,REC=1) TEXTA
      CLOSE(4)
1     WRITE(*,"('WAVELENGTH MINUMUM AND MAXIMUM: ',$)")
      READ(*,*) WMIN,WMAX
      IF(WMIN.EQ.0..OR.WMAX.EQ.0.) STOP
      KMIN=MAX0(1,NINT((WMIN-300.)/.4))
      KMAX=MIN0(1800,NINT((WMAX-300.)/.4))
      DO 4 I=1,45
      DO 4 J=1,90
      S=0.
      DO 3 K=KMIN,KMAX
3     S=S+IMA(I,J,K)
4     IM(I,J)=NINT(S/(KMAX-KMIN+1))
      OPEN(8,FILE='junk',ACCESS='DIRECT',RECL=8100,FORM=
     &'UNFORMATTED')
      WRITE(8,REC=1) IM
      CLOSE(8)
      GOTO 1
      END
